export const demoStores = [
  {
    name: 'Fashion Hub',
    description: 'Premier urban fashion destination featuring contemporary Western and fusion wear.',
    phone: '+91 98201 12345',
    email: 'fashionhub@nearstyle.local',
    address: 'Shop 14, Linking Road, Bandra West',
    city: 'Mumbai',
    area: 'Bandra',
    location: {
      type: 'Point',
      coordinates: [72.8335, 19.0607], // Longitude, Latitude
    },
    openingTime: '10:00 AM',
    closingTime: '09:30 PM',
    categories: ['Men', 'Women', 'Casual', 'Denim'],
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 42,
    status: 'APPROVED',
    allowsReservation: true,
  },
  {
    name: 'Urban Trends',
    description: 'Trendsetting streetwear, casual everyday staples, and premium denim collection.',
    phone: '+91 98202 23456',
    email: 'urbantrends@nearstyle.local',
    address: '772, 100 Feet Road, HAL 2nd Stage, Indiranagar',
    city: 'Bengaluru',
    area: 'Indiranagar',
    location: {
      type: 'Point',
      coordinates: [77.6408, 12.9784],
    },
    openingTime: '10:30 AM',
    closingTime: '10:00 PM',
    categories: ['Men', 'Women', 'Streetwear', 'Accessories'],
    image: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 38,
    status: 'APPROVED',
    allowsReservation: true,
  },
  {
    name: 'Style Studio',
    description: 'Bespoke tailoring, handcrafted ethnic kurtas, silk sarees, and festival collections.',
    phone: '+91 98203 34567',
    email: 'stylestudio@nearstyle.local',
    address: 'B-Block Inner Circle, Connaught Place',
    city: 'Delhi',
    area: 'Connaught Place',
    location: {
      type: 'Point',
      coordinates: [77.2195, 28.6315],
    },
    openingTime: '11:00 AM',
    closingTime: '09:00 PM',
    categories: ['Ethnic', 'Women', 'Men', 'Kurtas', 'Sarees'],
    image: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 56,
    status: 'APPROVED',
    allowsReservation: true,
  },
  {
    name: 'Trendy Wear',
    description: 'Chic women dresses, partywear, summer collections, and fashionable bags.',
    phone: '+91 98204 45678',
    email: 'trendywear@nearstyle.local',
    address: 'Plot 34, Road No 36, Jubilee Hills',
    city: 'Hyderabad',
    area: 'Jubilee Hills',
    location: {
      type: 'Point',
      coordinates: [78.4080, 17.4319],
    },
    openingTime: '10:00 AM',
    closingTime: '09:30 PM',
    categories: ['Women', 'Dresses', 'Partywear', 'Accessories'],
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    reviewCount: 29,
    status: 'APPROVED',
    allowsReservation: true,
  },
  {
    name: 'Urban Closet',
    description: 'Smart casuals, formal office shirts, trousers, and refined minimalist footwear.',
    phone: '+91 98205 56789',
    email: 'urbancloset@nearstyle.local',
    address: 'Level 1, Palladium Mall, Lower Parel',
    city: 'Mumbai',
    area: 'Lower Parel',
    location: {
      type: 'Point',
      coordinates: [72.8258, 18.9953],
    },
    openingTime: '11:00 AM',
    closingTime: '10:00 PM',
    categories: ['Men', 'Formal', 'Footwear', 'Casual'],
    image: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    reviewCount: 31,
    status: 'APPROVED',
    allowsReservation: true,
  },
  {
    name: 'Fashion Point',
    description: 'Youth fashion, graphic tees, relaxed denim, sneakers, and lifestyle accessories.',
    phone: '+91 98206 67890',
    email: 'fashionpoint@nearstyle.local',
    address: 'Shop 8, Koramangala 4th Block',
    city: 'Bengaluru',
    area: 'Koramangala',
    location: {
      type: 'Point',
      coordinates: [77.6271, 12.9345],
    },
    openingTime: '10:00 AM',
    closingTime: '09:00 PM',
    categories: ['Kids', 'Men', 'T-Shirts', 'Footwear'],
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 24,
    status: 'APPROVED',
    allowsReservation: true,
  },
];

export const demoProductsRaw = [
  // --- MEN SHIRTS & TEES ---
  {
    name: 'Classic Black Slim-Fit Oxford Shirt',
    brand: 'Urban Thread',
    category: 'Men',
    subcategory: 'Shirts',
    price: 1899,
    discountPrice: 1299,
    description: 'Tailored from 100% breathable organic cotton with button-down collar and durable stitching.',
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Black', 'Charcoal'],
    sizes: [
      { size: 'S', quantity: 4, reserved: 0 },
      { size: 'M', quantity: 8, reserved: 0 },
      { size: 'L', quantity: 6, reserved: 0 },
      { size: 'XL', quantity: 3, reserved: 0 },
    ],
    rating: 4.7,
    numReviews: 14,
  },
  {
    name: 'Navy Blue Linen Casual Shirt',
    brand: 'Highland Co.',
    category: 'Men',
    subcategory: 'Shirts',
    price: 2499,
    discountPrice: 1799,
    description: 'Breezy pure European linen shirt perfect for weekend strolls and smart-casual dinners.',
    images: [
      'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Navy Blue', 'Sky Blue'],
    sizes: [
      { size: 'M', quantity: 5, reserved: 0 },
      { size: 'L', quantity: 7, reserved: 0 },
      { size: 'XL', quantity: 2, reserved: 0 },
    ],
    rating: 4.8,
    numReviews: 9,
  },
  {
    name: 'Heavyweight Minimalist Cotton T-Shirt',
    brand: 'Studio Basics',
    category: 'Men',
    subcategory: 'T-Shirts',
    price: 999,
    discountPrice: 699,
    description: '240 GSM combed cotton with drop-shoulder relaxed silhouette that never shrinks.',
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['White', 'Off-White', 'Black'],
    sizes: [
      { size: 'S', quantity: 6, reserved: 0 },
      { size: 'M', quantity: 10, reserved: 0 },
      { size: 'L', quantity: 8, reserved: 0 },
      { size: 'XL', quantity: 5, reserved: 0 },
    ],
    rating: 4.6,
    numReviews: 22,
  },
  {
    name: 'Retro Typography Graphic Tee',
    brand: 'Street Vibe',
    category: 'Men',
    subcategory: 'T-Shirts',
    price: 1199,
    discountPrice: 799,
    description: 'Vintage Japanese streetwear typography with puff printing on breathable combed cotton.',
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Olive Green', 'Black'],
    sizes: [
      { size: 'M', quantity: 6, reserved: 0 },
      { size: 'L', quantity: 4, reserved: 0 },
    ],
    rating: 4.5,
    numReviews: 11,
  },
  {
    name: 'Burgundy Corduroy Overshirt',
    brand: 'Heritage Wear',
    category: 'Men',
    subcategory: 'Shirts',
    price: 2999,
    discountPrice: 2199,
    description: 'Thick plush corduroy overshirt with twin flap pockets and tonal horn buttons.',
    images: [
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Burgundy', 'Mustard'],
    sizes: [
      { size: 'S', quantity: 2, reserved: 0 },
      { size: 'M', quantity: 4, reserved: 0 },
      { size: 'L', quantity: 3, reserved: 0 },
    ],
    rating: 4.9,
    numReviews: 7,
  },

  // --- MEN JEANS & BOTTOMS ---
  {
    name: 'Vintage Washed Slim-Fit Indigo Jeans',
    brand: 'Raw Denim Lab',
    category: 'Men',
    subcategory: 'Jeans',
    price: 2799,
    discountPrice: 1999,
    description: 'Stretch denim with authentic whiskering, brass rivets, and five-pocket utility styling.',
    images: [
      'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Indigo Blue', 'Mid Wash'],
    sizes: [
      { size: 'S', quantity: 3, reserved: 0 },
      { size: 'M', quantity: 6, reserved: 0 },
      { size: 'L', quantity: 5, reserved: 0 },
      { size: 'XL', quantity: 2, reserved: 0 },
    ],
    rating: 4.7,
    numReviews: 18,
  },
  {
    name: 'Jet Black Relaxed Tapered Chinos',
    brand: 'Urban Thread',
    category: 'Men',
    subcategory: 'Jeans',
    price: 2199,
    discountPrice: 1599,
    description: 'Wrinkle-resistant twill fabric cut in a flattering tapered silhouette with flex waistband.',
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Jet Black', 'Khaki'],
    sizes: [
      { size: 'M', quantity: 4, reserved: 0 },
      { size: 'L', quantity: 5, reserved: 0 },
      { size: 'XL', quantity: 3, reserved: 0 },
    ],
    rating: 4.6,
    numReviews: 12,
  },

  // --- WOMEN DRESSES ---
  {
    name: 'Floral Print Tiered Summer Maxi Dress',
    brand: 'Aura Bloom',
    category: 'Women',
    subcategory: 'Dresses',
    price: 3499,
    discountPrice: 2499,
    description: 'Flowy georgette chiffon dress with sweetheart neckline, smocked back, and tiered skirt.',
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Blush Pink', 'Sage Green'],
    sizes: [
      { size: 'XS', quantity: 2, reserved: 0 },
      { size: 'S', quantity: 5, reserved: 0 },
      { size: 'M', quantity: 7, reserved: 0 },
      { size: 'L', quantity: 3, reserved: 0 },
    ],
    rating: 4.9,
    numReviews: 24,
  },
  {
    name: 'Classic Little Black Cocktail Dress',
    brand: 'Noir Elegance',
    category: 'Women',
    subcategory: 'Dresses',
    price: 3999,
    discountPrice: 2899,
    description: 'Structured crepe bodycon silhouette featuring an asymmetrical neckline and subtle slit.',
    images: [
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Midnight Black'],
    sizes: [
      { size: 'S', quantity: 3, reserved: 0 },
      { size: 'M', quantity: 6, reserved: 0 },
      { size: 'L', quantity: 2, reserved: 0 },
    ],
    rating: 4.8,
    numReviews: 19,
  },
  {
    name: 'Bohemian Embroidered Wrap Dress',
    brand: 'Boho Vibe',
    category: 'Women',
    subcategory: 'Dresses',
    price: 2999,
    discountPrice: 1999,
    description: 'Pure breathable rayon dress with delicate artisan floral threadwork and adjustable tie waist.',
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Terracotta', 'Ivory'],
    sizes: [
      { size: 'S', quantity: 4, reserved: 0 },
      { size: 'M', quantity: 5, reserved: 0 },
      { size: 'L', quantity: 3, reserved: 0 },
    ],
    rating: 4.6,
    numReviews: 15,
  },

  // --- ETHNIC WEAR (KURTAS & SAREES) ---
  {
    name: 'Chanderi Silk Festive Straight Kurta Set',
    brand: 'Virasat Heritage',
    category: 'Women',
    subcategory: 'Kurtas',
    price: 4499,
    discountPrice: 3299,
    description: 'Exquisite zari embroidery with matching straight pants and organza dupatta with scalloped borders.',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Emerald Green', 'Royal Maroon'],
    sizes: [
      { size: 'S', quantity: 3, reserved: 0 },
      { size: 'M', quantity: 6, reserved: 0 },
      { size: 'L', quantity: 4, reserved: 0 },
      { size: 'XL', quantity: 2, reserved: 0 },
    ],
    rating: 4.9,
    numReviews: 32,
  },
  {
    name: 'Handwoven Banarasi Silk Zari Saree',
    brand: 'Banaras Loom',
    category: 'Women',
    subcategory: 'Sarees',
    price: 7999,
    discountPrice: 5499,
    description: 'Authentic Banarasi Katan silk saree woven with intricate gold brocade floral motifs.',
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Crimson Red', 'Peacock Blue'],
    sizes: [
      { size: 'FREE', quantity: 6, reserved: 0 },
    ],
    rating: 5.0,
    numReviews: 28,
  },
  {
    name: 'Men Handloom Tussar Silk Kurta',
    brand: 'Virasat Heritage',
    category: 'Men',
    subcategory: 'Kurtas',
    price: 3299,
    discountPrice: 2299,
    description: 'Mandarin collar silk kurta with mother-of-pearl buttons and tailored welt pocket.',
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Ivory Gold', 'Deep Teal'],
    sizes: [
      { size: 'M', quantity: 5, reserved: 0 },
      { size: 'L', quantity: 6, reserved: 0 },
      { size: 'XL', quantity: 3, reserved: 0 },
    ],
    rating: 4.7,
    numReviews: 16,
  },
  {
    name: 'Cotton Chikankari Pastel Kurta Set',
    brand: 'Lucknowi Kraft',
    category: 'Women',
    subcategory: 'Kurtas',
    price: 2799,
    discountPrice: 1899,
    description: 'Handcrafted white thread Chikankari on soft mulmul fabric, paired with cropped palazzo.',
    images: [
      'https://images.unsplash.com/photo-1583391733975-22d4f26ca4a3?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Powder Blue', 'Lilac'],
    sizes: [
      { size: 'S', quantity: 4, reserved: 0 },
      { size: 'M', quantity: 5, reserved: 0 },
      { size: 'L', quantity: 3, reserved: 0 },
    ],
    rating: 4.8,
    numReviews: 17,
  },

  // --- FOOTWEAR ---
  {
    name: 'Classic White Leather Minimalist Sneakers',
    brand: 'SoleCraft',
    category: 'Footwear',
    subcategory: 'Shoes',
    price: 3499,
    discountPrice: 2499,
    description: 'Supple genuine nappa leather upper, memory foam ortholite insole, and cupsole durability.',
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['White', 'Triple Black'],
    sizes: [
      { size: 'S', quantity: 3, reserved: 0 }, // 7 UK
      { size: 'M', quantity: 6, reserved: 0 }, // 8 UK
      { size: 'L', quantity: 5, reserved: 0 }, // 9 UK
      { size: 'XL', quantity: 2, reserved: 0 }, // 10 UK
    ],
    rating: 4.8,
    numReviews: 35,
  },
  {
    name: 'Handcrafted Tan Leather Chelsea Boots',
    brand: 'Cobbler Co.',
    category: 'Footwear',
    subcategory: 'Shoes',
    price: 4999,
    discountPrice: 3699,
    description: 'Burnished full-grain Italian leather, elasticated side gussets, and Goodyear welted sole.',
    images: [
      'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Tan', 'Espresso Dark Brown'],
    sizes: [
      { size: 'M', quantity: 4, reserved: 0 },
      { size: 'L', quantity: 4, reserved: 0 },
      { size: 'XL', quantity: 2, reserved: 0 },
    ],
    rating: 4.9,
    numReviews: 21,
  },
  {
    name: 'Strappy Block Heel Sandal',
    brand: 'Aura Steps',
    category: 'Footwear',
    subcategory: 'Shoes',
    price: 2499,
    discountPrice: 1799,
    description: 'Comfortable 2.5-inch block heel with cushioned footbed and square open toe design.',
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Nude', 'Black'],
    sizes: [
      { size: 'S', quantity: 3, reserved: 0 },
      { size: 'M', quantity: 5, reserved: 0 },
      { size: 'L', quantity: 2, reserved: 0 },
    ],
    rating: 4.6,
    numReviews: 14,
  },

  // --- ACCESSORIES ---
  {
    name: 'Genuine Grain Leather Laptop Messenger Bag',
    brand: 'Craft & Hide',
    category: 'Accessories',
    subcategory: 'Accessories',
    price: 4999,
    discountPrice: 3499,
    description: 'Hand-stitched vintage oil-waxed leather with padded compartment fitting up to 15.6" laptops.',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Cognac Brown', 'Matte Black'],
    sizes: [
      { size: 'FREE', quantity: 8, reserved: 0 },
    ],
    rating: 4.9,
    numReviews: 18,
  },
  {
    name: 'Minimalist Automatic Chronograph Watch',
    brand: 'Aethel Watches',
    category: 'Accessories',
    subcategory: 'Accessories',
    price: 6499,
    discountPrice: 4899,
    description: 'Sapphire crystal glass, Japanese quartz movement, 50m water resistance, and mesh strap.',
    images: [
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Silver-White', 'Black Stealth'],
    sizes: [
      { size: 'FREE', quantity: 5, reserved: 0 },
    ],
    rating: 4.8,
    numReviews: 29,
  },
  {
    name: 'Polarized Acetate Square Sunglasses',
    brand: 'Solstice Optics',
    category: 'Accessories',
    subcategory: 'Accessories',
    price: 2199,
    discountPrice: 1499,
    description: 'UV400 protection with TAC polarized lenses and premium Italian hand-polished acetate frame.',
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Tortoiseshell', 'Glossy Black'],
    sizes: [
      { size: 'FREE', quantity: 12, reserved: 0 },
    ],
    rating: 4.7,
    numReviews: 15,
  },

  // --- KIDS COLLECTION ---
  {
    name: 'Organic Cotton Printed Dungaree Set',
    brand: 'Little Sprout',
    category: 'Kids',
    subcategory: 'Dresses',
    price: 1599,
    discountPrice: 1099,
    description: 'Super-soft GOTS certified organic cotton corduroy dungaree with snap buttons for easy wear.',
    images: [
      'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Mustard Yellow', 'Denim Blue'],
    sizes: [
      { size: 'S', quantity: 4, reserved: 0 }, // 2-3Y
      { size: 'M', quantity: 6, reserved: 0 }, // 4-5Y
      { size: 'L', quantity: 3, reserved: 0 }, // 6-7Y
    ],
    rating: 4.8,
    numReviews: 11,
  },
  {
    name: 'Kids Graphic Cotton Tee & Shorts Combo',
    brand: 'Little Sprout',
    category: 'Kids',
    subcategory: 'T-Shirts',
    price: 1299,
    discountPrice: 849,
    description: 'Breathable, playful dinosaur print set with elastic waistband and contrast drawstrings.',
    images: [
      'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=800&q=80',
    ],
    colors: ['Sky Blue', 'Mint Green'],
    sizes: [
      { size: 'S', quantity: 5, reserved: 0 },
      { size: 'M', quantity: 5, reserved: 0 },
      { size: 'L', quantity: 4, reserved: 0 },
    ],
    rating: 4.7,
    numReviews: 8,
  },
];
